# Generated by Django 4.2.3 on 2023-08-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('event_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=240, verbose_name='EventName')),
                ('date', models.DateField(verbose_name='Registration Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('location', models.CharField(max_length=300, verbose_name='Location')),
                ('image', models.CharField(max_length=200, verbose_name='image')),
                ('is_liked', models.BooleanField(default=False, verbose_name='is_liked')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=240, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=240, verbose_name='Password')),
                ('registrationDate', models.DateField(auto_now_add=True, verbose_name='Registration Date')),
            ],
        ),
    ]
