# Generated by Django 4.2.3 on 2023-08-03 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='event_id',
            new_name='id',
        ),
    ]
